export const CACHE_KEY_CONSUMERS = "CONSUMERS";
export const CACHE_KEY_DRIVERS = "DRIVERS";

export const CACHE_KEY_ADDRESSES = "ADDRESSES";

export const CACHE_KEY_OPTIMIZED_ROUTE = "OPTIMIZED_ROUTE";
